### ISSUE TITLE
Attributes in Assemblies

### ISSUE THREAD

**Issue by markusvoelter** [mbeddr/mbeddr.formal#12]
Our components have internal state, for example, a failure_count. This is used in contracts. RIght now it looks as if it is not possible to have properties/variables/attributes in assemblies. Is this planned?

**Comment by danielratiu** [comment]
Currently we support annotating SMV modules with contracts. In those contracts one can reference internal variables defined in modules. Would this be enough for your use-cases?

**Comment by danielratiu** [comment]
talked to Markus and it is OK for now
