### ISSUE TITLE
Gradle exception: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by norro** [mbeddr/mbeddr.formal#13]
Gradle build of master fails with error message `Execution failed for task ':build_allScripts'. java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String`, see https://build.mbeddr.com/viewLog.html?buildId=269833&tab=buildResultsDiv&buildTypeId=Mbeddr2_Mbeddr_Gradle_Fasten_Build

Can't locate it more precisely, yet. Seems to be somewhere in [build/scripts/build_all_scripts.xml](https://github.com/mbeddr/mbeddr.formal/blob/master/build/scripts/build_all_scripts.xml), though.

**Comment by norro** [comment]
@danielratiu I looked around for a while now and can't find the reason (also die to the fact that I am quite new to gradle). Could you please have a look if you find the cause?

**Comment by wsafonov** [comment]
Added an explicit cast to String to work around the cast issue in the mps gradle plugin (commit 1013dff3419c210db2caf82973a8f641dd648266).
