### ISSUE TITLE
Gradle Exception: Could not set unknown property 'archiveBaseName'

### ISSUE THREAD

**Issue by BentleyJOakes** [mbeddr/mbeddr.formal#14]
On commit:
42ef418e9a196aa2e6d9da4ed3d5383acc376273 (master)

When running:
`gradle`

Full Exception:
`Could not set unknown property 'archiveBaseName' for task ':packageNuSMV' of type org.gradle.api.tasks.bundling.Zip.`

Relevant code:
`task packageNuSMV(type: Zip, dependsOn: build_smv_languages) {`
`    archiveBaseName = 'com.mbeddr.formal.nusmv'`
`    from artifactsDir`
`    include 'com.mbeddr.formal.nusmv/**'`
`}`

Please let me know what other information is required.

Edit: Gradle version
Gradle 4.4.1

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.6 compiled on July 11 2019
JVM:          11.0.5-ea (Ubuntu 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OS:           Linux 5.3.0-23-generic amd64

Second Edit:
Seems to be caused by the Gradle version < 5. Note that this is on Ubuntu 19.10.

**Comment by danielratiu** [comment]
@BentleyJOakes - sorry, we have not experimented with building under Linux (only under Windows) 

Does this work now? Could you go further?

**Comment by BentleyJOakes** [comment]
Yes I can now go further. Sorry for the noise.
