### ISSUE TITLE
Gradle Exception: Buildfile: build-nusmv-languages.xml does not exist

### ISSUE THREAD

**Issue by BentleyJOakes** [mbeddr/mbeddr.formal#17]
On commit:
8167cf2

When running:
`./gradlew build_smv_languages`

Full Exception:
`> Task :build_smv_languages FAILED`
`Buildfile: /home/boakes/Projects/FASTEN/build/scripts/build-nusmv-languages.xml does not exist!`
`Build failed`

Relevant code:
`task build_smv_languages(type: BuildLanguages, dependsOn: [build_allScripts]) {`
`    script new File("$buildDir/scripts/build-nusmv-languages.xml")`
`}`

Gradle Version:
Gradle 5.5

Build time:   2019-06-28 17:36:05 UTC
Revision:     83820928f3ada1a3a1dbd9a6c0d47eb3f199378f

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.5-ea (Ubuntu 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OS:           Linux 5.3.0-23-generic amd64

Please let me know any other information you require.

**Comment by danielratiu** [comment]
gradle generates this automatically by running a bootstrap script called "build_all_scripts.xml" which is under the version control.

Have you set the variables in "gradle.properties" ?

**Comment by BentleyJOakes** [comment]
There is no gradle.properties file in the repo. What parameters are needed?

And from a look at build_all_scripts.xml, I don't see where the build-nusmv-languages.xml file is built. Is it created from within MPS code?

**Comment by danielratiu** [comment]
there is a gradle.properties.example file in the root - please rename it into gradle.properties and set the variables.

build-nusmv-languages.xml is generated from MPS by the build-allScripts script
(you can generate them manually and build everything my opening the nusmv project)

@BentleyJOakes  please let me know if it works ...

**Comment by BentleyJOakes** [comment]
I've opened the code/languages/com.mbeddr.formal.nusmv project in MPS.

As a note to anyone trying this, the path variable `mbeddr.formal.home` must be set in Settings->Appearance & Behavior->Path Variables.

Most of the Languages and Solutions in the nusmv project have build errors.

When I try to run model check on all the languages, I receive the following Exception:
> java.lang.IllegalArgumentException : Illegal parameter : com.mbeddr.mpsutil.blutil.structure.SafeReadAction is not a subconcept of jetbrains.mps.baseLanguage.structure.ILocalVariableElement [node r:6e82d8d0-32f5-4302-ba79-fcd365c09c01(com.mbeddr.formal.base.operatorspanel.editor)/2707707741267927230]

Another issue:
When I rebuild com.mbeddr.formal.base (just as a starting point), I get the error
> Can't find imported model: de.itemis.mps.editor.celllayout.runtime.cells

A third issue:
When I try to rebuild the build script (com.mbeddr.formal.allScripts) I get the error
> Can't find imported model: com.mbeddr.mpsutil.dev.build

Am I missing a dependency?

**Comment by danielratiu** [comment]
@BentleyJOakes thank you for this feedback! 

Most likely you are missing the mbeddr.platform plugins. I have updated the readme description about how to build FASTEN from within MPS.

https://github.com/mbeddr/mbeddr.formal/blob/master/README.md

Please let me know if it works.

**Comment by BentleyJOakes** [comment]
Thank you!

Issues found:
1) I had an error marked by MPS in `com.mbeddr.formal.allScripts.build.allScripts.com.mbeddr.formal.allScripts`
I had to add the last three lines here. 
```
solution com.mbeddr.formal.nusmv.build (7125ed76-a460-4b0f-b95b-a899f99488d6) 
  load from $mbeddr.formal.nusmv.code/solutions/com.mbeddr.formal.nusmv.build/com.mbeddr.formal.nusmv.build.msd 
  content: 
    (with sources) 
    resources files from $mbeddr.formal.home/code/languages/com.mbeddr.formal.nusmv/solutions/com.mbeddr.formal.nusmv.build 
      includes icons/** 
  dependencies: 
    (extracted) jetbrains.mps.ide.build 
    (extracted) JDK 
    (extracted) de.itemis.mps.extensions.build 
    (extracted) org.apache.commons 
    (extracted) com.mbeddr.platform 
```

2)
In com.mbeddr.formal.nusmv.build.com.mbeddr.formal.nusmvTests, I had to add two macro lines
```
folder dependencies.root = $mbeddr.formal.home/build/dependencies 
folder dependencies.mbeddr.platform = $dependencies.root/com.mbeddr.platform
```

3)
In com.mbeddr.formal.nusmv.build.com.mbeddr.formal.nusmv, I had to add two dependencies (the last two lines):
```
idea plugin com.mbeddr.formal.nusmv from generated by default 'plugin.xml' descriptor file 
  name com.mbeddr.formal.nusmv 
  short (folder) name com.mbeddr.formal.nusmv 
  version ${version} 
  content: 
    com.mbeddr.formal.nusmv 
    com.mbeddr.formal.nusmv.devkit 
  dependencies: 
    jetbrains.mps.core 
    de.slisson.mps.tables 
    org.apache.commons 
    com.mbeddr.mpsutil 
```

4) Your path to mps.home is hard-coded in these files. Perhaps it should also be a path variable?
*  `com.mbeddr.formal.allScripts.build.allScripts.com.mbeddr.formal.allScripts`
*  `com.mbeddr.formal.nusmv.build.com.mbeddr.formal.nusmv`
*  `com.mbeddr.formal.nusmv.build.com.mbeddr.formal.nusmvDistribution`
*  `com.mbeddr.formal.nusmv.build.com.mbeddr.formal.nusmvTests`

**Comment by danielratiu** [comment]
On my machine these dependencies are in place. Only the path to "mps_home" should differ from a machine to another.

Does the gradlew based build work on your machine?

**Comment by BentleyJOakes** [comment]
Yes, now the gradlew build is working. I've just opened my built version of FASTEN and am testing it.

**Comment by danielratiu** [comment]
Thank you for reporting these ... if it works, please close the issue :-)
