### ISSUE TITLE
Use NuSMV show_property and LTLSPEC names for unique mapping

### ISSUE THREAD

**Issue by mfgpcm** [mbeddr/mbeddr.formal#18]
Currently, the .source file for nusmv is generated but not used. By adding `show_property` to the .source file, nusmv outputs a list of the LTLSPEC given in the .smv file including the name (if given, e.g. by `LTLSPEC NAME x := true`).
By adding unique names to LTLSPECs, running nusmv on the .source file and updating the class `AGResultsLifter` to support the additional output, the lifting of nusmv results could be improved. This is especially beneficial for vacuity checks of contracts that belong to the same component.

**Comment by danielratiu** [comment]
I have just added show_property. Will look into lifting the following days.

**Comment by danielratiu** [comment]
I have fixed this - the results lifter now takes into consideration the info displayed by the show_properties (if available)
