### ISSUE TITLE
Add unix nusmv

### ISSUE THREAD

**Issue by norro** [mbeddr/mbeddr.formal#21]
Currently mbeddr.formal/rcp_resources/external_tools/ only contains nusmw.exe. We should add unix nusmv as well

**Comment by danielratiu** [comment]
I do not have access to unix machines - could you please add the unix (linux?) executable and test that the tool-runner can successfully start.

**Comment by danielratiu** [comment]
@norro I think that this is fixed as well - I am closing for now but feel free to re-open it if the linux binaries are not there (I saw linux binaries but cannot test)
