### ISSUE TITLE
Add safety (gsn, req, spin) to FASTEn distribution

### ISSUE THREAD

**Issue by norro** [mbeddr/mbeddr.formal#24]
Currently, `build-fasten-distribution.xml` only bundles nuSMV languages and devkit. This is misleading, so I suggest to
* rename current _build-fasten-distribution.xml_ to _build-nusmv-distribution.xml_ and
* add _real_ FASTEN distribution build that encompasses nusmv, spin, req, safety, etc.

**Comment by norro** [comment]
@danielratiu does this make sense?

**Comment by danielratiu** [comment]
@norro in the fasten.safety project there is a build script which packages more things (including guns, spin, stpa)

we also distribute this via our RCP
https://sites.google.com/site/fastenroot/home

would this suffice to your needs?

**Comment by danielratiu** [comment]
@norro is this issue still open? I think that it is resolved - what do you think? If yes, please close this

**Comment by norro** [comment]
Absolutely, this works lovely now. Thanks for the reminder, I am closing the issue.
