### ISSUE TITLE
Integer keyword undefined for nusmv

### ISSUE THREAD

**Issue by BentleyJOakes** [mbeddr/mbeddr.formal#27]
Hello,

I defined the simple system in FASTEN:
```
TestSystem                     
model   TestSol.test_model                          
------------------------------ 
interface TestInter            
  a : integer => b : integer   
contract:                      
  no contract                  
                               
assembly TestAssembly          
  no input => no output        
contract:                      
  no contract                  
  body: TestInter one;         
        TestInter two;         
        connect one.b to two.a;
```

When I right-click the assembly, and hit Check AG, I receive the following error message from nusmv:

`solutions/TestSol/source_gen/TestSol/test_model/TestAssembly___flattenedSystem.smv: line 3: "integer" undefined`

Here is the generated artifact:

```
MODULE TestAssembly___flattened
  VAR
    one_DOT_a : integer;
    one_DOT_b : integer;
    two_DOT_a : integer;
    two_DOT_b : integer;
    
  DEFINE
    arch_wiring := (one_DOT_b = two_DOT_a);
  
MODULE main
  VAR
    flattened : TestAssembly___flattened;
```

The nusmv manual says that integer is a valid keyword, so I don't understand what is the issue here.

I also noticed that none of the tutorial examples in FASTEN use the integer keyword. Perhaps there is an issue here that's not being tested in the tutorial examples?

Thanks for any help you can give.

**Comment by danielratiu** [comment]
Hi Bentley,

this is not a FASTEN issue but rather a limitation of NuSMV. Could you try to see if nuXmv accepts integers (AFAIK it does). Beware that you need to download yourself nuXmv and that it has a restricted license ...

If you really need integers, then try nuXmv (download it, rename numb -> nusmv and replace your nusmv binary). 

If using intervals is enough, you could typedef an interval and use the symbolic name (see screenshot)

<img width="259" alt="image" src="https://user-images.githubusercontent.com/1437141/81302997-69e1bc00-907b-11ea-8f98-dc17019dbc66.png">

**Comment by BentleyJOakes** [comment]
Hi Daniel,

Thanks for the quick response. Yes, using intervals works for me.
Sorry for the noise. I assumed that FASTEN was tied to only NuSMV, so everything exposed in the editor could be verified by NuSMV.
