### ISSUE TITLE
GSN: show text of referenced goal in away goal

### ISSUE THREAD

**Issue by mfgpcm** [mbeddr/mbeddr.formal#40]
When creating a GSN and adding an away goal, it would be beneficial to see the description of the referenced goal in the away goal directly.
@norro as discussed, please take over from here.

**Comment by danielratiu** [comment]
The Away Goals per se are deprecated. The reason for this is that we have specialized goals (e.g. requirements verification) that can be away as well. Now, each goal can be made "away" in inspector.

The best way of working is to use the intention "Make Away Goal" - that extracts automatically a new goal structure with a root goal that is pointed from the original goal. The type, text, properties remain the same.

![image](https://user-images.githubusercontent.com/1437141/90387557-ad8a8f80-e086-11ea-8090-82201dcc7196.png)

**Comment by bkolb** [comment]
Zu sein scheint die Situation Situation in U

danielratiu <notifications@github.com> schrieb am Mi. 19. Aug. 2020 um
13:50:
