### ISSUE TITLE
Snapshot 2020-07-28 zip contains paths that are too long

### ISSUE THREAD

**Issue by Bazmundi** [mbeddr/mbeddr.formal#55]
Getting errors reported with unzipping Snapshot 2020-07-28 sources.   Filepath too long.

On windoze 10.

**Comment by danielratiu** [comment]
@Bazmundi does this happen only to the sources distribution? Is the binary distribution working fine?

If you want sources, you could clone the repo and checkout the corresponding branch ... maintenance/xyz
The current master is not that far either from the last release.

**Comment by Bazmundi** [comment]
Yes. It was fixed by renaming the zip to a muxh shorter string.
