### ISSUE TITLE
changes in core analyes 

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.formal#56]
I'm not sure if you are using the infrastructure from core analyses to run your tools. If so I introduced a change in some of the classes related to the tool runners to be able to pass the repository down to the part of the code that loads the text gen traces. That code was still using global model access. I removed that usage and hat to change some method signatures. This is required for MPS 2020.3 but was introduced in master today as part of the 2020.2 migration. 

https://github.com/mbeddr/mbeddr.core/commit/94154375a263c1da53ef9dbf9d61b24f5f0e1db8

**Comment by danielratiu** [comment]
@coolya thank you - everything looks good here ...

**Comment by danielratiu** [comment]
I am closing now this issue (to minimize dependencies, FASTEN has its own tool runner)
