### ISSUE TITLE
Signed and unsigned word not permitted as type

### ISSUE THREAD

**Issue by robertguetzkow** [mbeddr/mbeddr.formal#61]
I was trying to extend the `_010_traffic_lights_controller_baseLang` example with additional variables and noticed that FASTEN doesn't seem to accept variables of type `unsigned word [N]` and `signed word [N]`. Is this a user error or does FASTEN limit the allowed types for state machines?
             
```
  VAR {                                                                       
    state variable traffic : {Green, Yellow, Red};                            
    pedestrian : {Walk, DontWalk};                                            
    timer : 0..10;                                                            
    abc : signed word [5];                                                    
  }
```                                                                                                                                                        

Error message on hover:
`Abstract concept instance detected. Use one of sub-concepts instead. Concept: Type`

Apologies if this is a trivial mistake caused by my inexperience with FASTEN and NuSMV.

**Comment by danielratiu** [comment]
If you type "word" and start auto-completion (ctrl+space)  then FASTEN creates an "unsigned word"

![image](https://user-images.githubusercontent.com/1437141/115456081-0cf6fb80-a223-11eb-9104-cf12bd88d463.png)

Please confirm that it works like this.

If you want to change the signedness (i.e. to "signed") there is an intention (alt + enter) - unfortunately it seems that there is an MPS bug which prevents correct functioning of this intention. I have commited a fix on FASTEN side to avoid the MPS issue
https://youtrack.jetbrains.com/issue/MPS-33284

Workaround for changing the signedness - right click on the type, select "show reflective editor" and change the "signed" flag.

**Comment by robertguetzkow** [comment]
Thank you for the quick reply. That seems to do the trick.
