### ISSUE TITLE
Unable to change case expression's auto-generated "otherwise" basic expression

### ISSUE THREAD

**Issue by robertguetzkow** [mbeddr/mbeddr.formal#62]
It seems that it is currently not possible to alter the auto-generated `otherwise` case in a case-expression when using the DSL for `STATE-MACHINE`. This prevents the default case from altering state variables. For instance it is not possible to decremented a counter/timer whenever none of the guard conditions are true. While the `_040_state_machines` documentation states that the DSL restricts the NuSMV base language, it doesn't mention this restriction.

**Comment by ratiud** [comment]
thank you for reporting the issues about the documentation - I have just fixed them
